"use client";

import { Box, Typography, Card } from "@mui/material";
import { FolderOpen } from "lucide-react";

export default function AdminDocumentsPage() {
  return (
    <Box>
      <Box sx={{ mb: 4 }}>
        <Typography variant="h5" sx={{ fontWeight: 700, color: "#111827" }}>
          Documents
        </Typography>
        <Typography variant="body2" sx={{ color: "#6B7280", mt: 0.5 }}>
          View all documents generated by your firm's staff
        </Typography>
      </Box>

      <Card
        elevation={0}
        sx={{ border: "1px dashed #D1D5DB", borderRadius: 2, p: 6, textAlign: "center" }}
      >
        <Box sx={{ bgcolor: "#F0FDF4", p: 2, borderRadius: "50%", display: "inline-flex", mb: 2 }}>
          <FolderOpen size={32} color="#395B45" />
        </Box>
        <Typography variant="h6" sx={{ fontWeight: 600, color: "#111827", mb: 1 }}>
          Generated Documents
        </Typography>
        <Typography variant="body2" sx={{ color: "#6B7280", maxWidth: 440, mx: "auto" }}>
          Once staff members generate DOCX documents from templates, all generated files
          will appear here. You can view, download, and audit all documents created within your firm.
        </Typography>
        <Typography
          variant="caption"
          sx={{
            display: "inline-block",
            mt: 3,
            px: 2,
            py: 0.75,
            bgcolor: "#FEF3C7",
            color: "#92400E",
            borderRadius: 2,
            fontWeight: 500,
          }}
        >
          Coming in next phase
        </Typography>
      </Card>
    </Box>
  );
}
